# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_lifetime: 7776000
        cookie_httponly: true
        cookie_samesite: lax
        cookie_secure: auto
        gc_maxlifetime: 7776000

    rate_limiter:
        wave_search_history:
            policy: sliding_window
            limit: 30
            interval: '1 minute'
        wave_credit_redeem:
            policy: sliding_window
            limit: 10
            interval: "15 minutes"
        wave_login_ip:
            policy: sliding_window
            limit: 30
            interval: '15 minutes'
        wave_login_identity:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
        wave_register_ip:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
        wave_verification_ip:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
        wave_verification_identity:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
        wave_password_reset_ip:
            policy: sliding_window
            limit: 10
            interval: '1 hour'
        wave_password_reset_identity:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
        wave_contact_ip:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
        wave_newsletter_ip:
            policy: sliding_window
            limit: 5
            interval: '1 hour'

    #esi: true
    #fragments: true
