monolog:
    channels: # To see all channels, run bin/console debug:autowiring logger
        - background
        - search
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    handlers:
        search:
            type: rotating_file
            path: "%kernel.logs_dir%/search.log"
            max_files: "%env(int:LOG_RETENTION_DAYS)%"
            level: info
            channels: [search]
            formatter: monolog.formatter.json
