<?php

declare(strict_types=1);

namespace App\Tests\Migration;

use App\Migration\LegacySqlCompatibility;
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Comparator;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use PHPUnit\Framework\TestCase;
use Psr\Log\NullLogger;

final class LegacySqlCompatibilityTest extends TestCase
{
    public function testConvertsSqliteGeneratedSchemaToPostgreSql(): void
    {
        $sql = 'CREATE TABLE campaign (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, channels CLOB NOT NULL, description CLOB NOT NULL, closes_at DATETIME NOT NULL, featured BOOLEAN DEFAULT 0 NOT NULL, CONSTRAINT FK_campaign_company FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)';

        $converted = LegacySqlCompatibility::forPostgreSql($sql);

        self::assertStringContainsString('id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL', $converted);
        self::assertStringContainsString('PRIMARY KEY (id)', $converted);
        self::assertStringContainsString('channels JSON NOT NULL', $converted);
        self::assertStringContainsString('description TEXT NOT NULL', $converted);
        self::assertStringContainsString('closes_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL', $converted);
        self::assertStringContainsString('featured BOOLEAN DEFAULT FALSE NOT NULL', $converted);
        self::assertStringNotContainsString('AUTOINCREMENT', $converted);
        self::assertStringNotContainsString('CLOB', $converted);
        self::assertStringNotContainsString('DATETIME', $converted);
    }

    public function testIdentitySequenceResetPreservesExplicitIds(): void
    {
        self::assertSame(
            "SELECT setval(pg_get_serial_sequence('campaign', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM campaign",
            LegacySqlCompatibility::identityResetSql('campaign'),
        );
    }

    public function testRejectsUnsafeIdentitySequenceTableNames(): void
    {
        $this->expectException(\InvalidArgumentException::class);

        LegacySqlCompatibility::identityResetSql('campaign; DROP TABLE wave_user');
    }

    public function testHistoricalMigrationsPlanWithPostgreSqlSql(): void
    {
        $connection = DriverManager::getConnection([
            'driver' => 'pdo_sqlite',
            'memory' => true,
        ]);
        $platform = new PostgreSQLPlatform();
        $comparator = new Comparator($platform);
        $platformProperty = new \ReflectionProperty(AbstractMigration::class, 'platform');
        $files = glob(dirname(__DIR__, 2).'/migrations/Version*.php');
        self::assertNotFalse($files);

        foreach ($files as $file) {
            require_once $file;
        }

        $unsupportedSqliteSyntax = '/AUTOINCREMENT|\bCLOB\b|\bDATETIME\b|\bBOOLEAN\s+DEFAULT\s+[01]\b/i';
        $statementsByMigration = [];

        foreach ($files as $file) {
            $class = 'DoctrineMigrations\\'.pathinfo($file, PATHINFO_FILENAME);
            $migration = new $class($connection, new NullLogger());
            $platformProperty->setValue($migration, $platform);
            // Earlier migrations add tables through SQL, so their changes are not
            // reflected in this disconnected schema. Supply the existing creator
            // table for later schema-based alterations, as Doctrine does at runtime.
            $before = new Schema();
            $creator = $before->createTable('creator');
            $creator->addColumn('id', 'integer', ['autoincrement' => true]);
            $creator->setPrimaryKey(['id']);
            $schema = clone $before;
            $migration->up($schema);
            $statements = array_map(
                static fn ($query): string => $query->getStatement(),
                $migration->getSql(),
            );
            $statements = [...$statements, ...$platform->getAlterSchemaSQL($comparator->compareSchemas($before, $schema))];
            $statementsByMigration[$class] = $statements;

            foreach ($statements as $statement) {
                self::assertDoesNotMatchRegularExpression(
                    $unsupportedSqliteSyntax,
                    $statement,
                    $class.' contains SQLite-only migration syntax.',
                );
            }
        }

        self::assertStringNotContainsString(
            'DROP TABLE campaign',
            implode("\n", $statementsByMigration['DoctrineMigrations\\Version20261002173924']),
        );
        self::assertStringNotContainsString(
            'DROP TABLE company',
            implode("\n", $statementsByMigration['DoctrineMigrations\\Version20261002180752']),
        );
        self::assertStringContainsString(
            'ADD GENERATED BY DEFAULT AS IDENTITY',
            implode("\n", $statementsByMigration['DoctrineMigrations\\Version20261003122500']),
        );
        self::assertStringContainsString(
            "ALTER TABLE creator ADD creator_types JSON DEFAULT '[]' NOT NULL",
            implode("\n", $statementsByMigration['DoctrineMigrations\\Version20261008150000']),
        );
    }
}
