<?php

declare(strict_types=1);

namespace App\Migration;

final class LegacySqlCompatibility
{
    private const JSON_COLUMNS = [
        'answers',
        'categories',
        'channels',
        'deliverables',
        'faqs',
        'labels',
        'packages',
        'portfolio',
        'questions',
        'selected_packages',
        'social_profiles',
        'social_links',
        'tags',
        'translations',
    ];

    public static function identityTableForCreateStatement(string $sql): ?string
    {
        if (preg_match('/CREATE\s+TABLE\s+([a-z_][a-z0-9_]*)\s*\(/i', $sql, $tableMatch) !== 1
            || preg_match('/\bid\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\s+NOT\s+NULL\b/i', $sql) !== 1
        ) {
            return null;
        }

        return strtolower($tableMatch[1]);
    }

    public static function forPostgreSql(string $sql): string
    {
        $identityTable = self::identityTableForCreateStatement($sql);

        $jsonColumnPattern = '/\b('.implode('|', self::JSON_COLUMNS).')\s+CLOB\b/i';
        $sql = preg_replace($jsonColumnPattern, '$1 JSON', $sql) ?? $sql;
        $sql = preg_replace('/\bCLOB\b/i', 'TEXT', $sql) ?? $sql;
        $sql = preg_replace('/\bDATETIME\b/i', 'TIMESTAMP(0) WITHOUT TIME ZONE', $sql) ?? $sql;
        $sql = preg_replace('/\bBOOLEAN\s+DEFAULT\s+0\b/i', 'BOOLEAN DEFAULT FALSE', $sql) ?? $sql;
        $sql = preg_replace('/\bBOOLEAN\s+DEFAULT\s+1\b/i', 'BOOLEAN DEFAULT TRUE', $sql) ?? $sql;

        if ($identityTable === null) {
            return $sql;
        }

        $sql = preg_replace(
            '/\bid\s+INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\s+NOT\s+NULL\b/i',
            'id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL',
            $sql,
            1,
        ) ?? $sql;

        $hasTerminatingSemicolon = str_ends_with(rtrim($sql), ';');
        $statement = rtrim($sql, " \t\n\r\0\x0B;");
        $closingParenthesis = strrpos($statement, ')');

        if ($closingParenthesis === false) {
            return $sql;
        }

        $statement = substr($statement, 0, $closingParenthesis)
            .', PRIMARY KEY (id)'
            .substr($statement, $closingParenthesis);

        return $hasTerminatingSemicolon ? $statement.';' : $statement;
    }

    public static function identityResetSql(string $table): string
    {
        if (preg_match('/^[a-z_][a-z0-9_]*$/', $table) !== 1) {
            throw new \InvalidArgumentException('Invalid table name for identity sequence reset.');
        }

        return sprintf(
            "SELECT setval(pg_get_serial_sequence('%1\$s', 'id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM %1\$s",
            $table,
        );
    }
}
