<?php

namespace App\Account;

final class MarketplaceEmailCopy
{
    private const COPY = [
        'bs' => [
            'application_received' => [
                'subject' => 'Nova prijava za kampanju na Waveu',
                'preheader' => 'Novi kreator se prijavio na tvoju kampanju.',
                'eyebrow' => 'NOVA PRIJAVA',
                'heading' => 'Stigla je nova prijava za kampanju.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj prijavu kreatora i njegovu poruku prije nego što odlučiš o sljedećem koraku.',
                'firstLabel' => 'Kreator',
                'secondLabel' => 'Kampanja',
                'detailsLabel' => 'Poruka prijave',
                'buttonLabel' => 'Pregledaj prijave',
                'footer' => 'Automatska poruka od Wavea. Molimo ne odgovaraj na ovu e-poruku.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'Novi upit za tvoj paket na Waveu',
                'preheader' => 'Kompanija je izabrala paket sa tvog profila.',
                'eyebrow' => 'NOVI UPIT ZA SARADNJU',
                'heading' => 'Kompanija je poslala upit za tvoj paket.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj odabrane pakete, predloženi budžet i poruku kompanije.',
                'firstLabel' => 'Kompanija',
                'secondLabel' => 'Kreator',
                'detailsLabel' => 'Odabrani paketi i poruka',
                'buttonLabel' => 'Pregledaj upite',
                'footer' => 'Automatska poruka od Wavea. Molimo ne odgovaraj na ovu e-poruku.',
                'selectedPackagesLabel' => 'Odabrani paketi',
                'servicePackage' => 'Paket usluga',
                'otherOption' => 'Nešto drugo',
                'proposedAmountLabel' => 'Predloženi budžet',
                'companyMessageLabel' => 'Poruka kompanije',
                'noPackages' => 'Nijedan paket nije izabran',
                'priceByAgreement' => 'Po dogovoru',
            ],
            'creator_hired' => [
                'subject' => 'Ponuda je prihvaćena na Waveu',
                'preheader' => 'Tvoj angažman za kampanju je potvrđen.',
                'eyebrow' => 'ANGAŽMAN POTVRĐEN',
                'heading' => 'Čestitamo, angažovan/a si!',
                'greeting' => 'Zdravo!',
                'message' => 'Kompanija te je angažovala za ovu kampanju nakon što si prihvatio/la ponudu.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Kompanija',
                'detailsLabel' => 'Status ponude',
                'details' => 'Prihvaćena',
                'buttonLabel' => 'Pogledaj ponudu',
                'footer' => 'Automatska poruka od Wavea. Molimo ne odgovaraj na ovu e-poruku.',
            ],
            'unread_message_reminder' => [
                'subject' => 'Imaš nepročitane poruke na Waveu',
                'preheader' => 'U razgovoru o kampanji čeka te nova poruka.',
                'eyebrow' => 'NEPROČITANE PORUKE',
                'heading' => 'Čeka te nova poruka.',
                'greeting' => 'Zdravo!',
                'message' => 'U razgovoru o kampanji imaš nepročitane poruke. Otvori Wave da nastaviš razgovor.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Pošiljalac',
                'detailsLabel' => 'Broj nepročitanih poruka',
                'buttonLabel' => 'Otvori razgovor',
                'footer' => 'Automatska poruka od Wavea. Molimo ne odgovaraj na ovu e-poruku.',
            ],
        ],
        'hr' => [
            'application_received' => [
                'subject' => 'Nova prijava za kampanju na Waveu',
                'preheader' => 'Novi se kreator prijavio na tvoju kampanju.',
                'eyebrow' => 'NOVA PRIJAVA',
                'heading' => 'Stigla je nova prijava za kampanju.',
                'greeting' => 'Pozdrav!',
                'message' => 'Pregledaj prijavu kreatora i njegovu poruku prije nego što odlučiš o sljedećem koraku.',
                'firstLabel' => 'Kreator',
                'secondLabel' => 'Kampanja',
                'detailsLabel' => 'Poruka prijave',
                'buttonLabel' => 'Pregledaj prijave',
                'footer' => 'Automatska poruka Wavea. Molimo ne odgovaraj na ovu poruku.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'Novi upit za tvoj paket na Waveu',
                'preheader' => 'Tvrtka je odabrala paket s tvog profila.',
                'eyebrow' => 'NOVI UPIT ZA SURADNJU',
                'heading' => 'Tvrtka je poslala upit za tvoj paket.',
                'greeting' => 'Pozdrav!',
                'message' => 'Pregledaj odabrane pakete, predloženi budžet i poruku tvrtke.',
                'firstLabel' => 'Tvrtka',
                'secondLabel' => 'Kreator',
                'detailsLabel' => 'Odabrani paketi i poruka',
                'buttonLabel' => 'Pregledaj upite',
                'footer' => 'Automatska poruka Wavea. Molimo ne odgovaraj na ovu poruku.',
                'selectedPackagesLabel' => 'Odabrani paketi',
                'servicePackage' => 'Paket usluga',
                'otherOption' => 'Nešto drugo',
                'proposedAmountLabel' => 'Predloženi budžet',
                'companyMessageLabel' => 'Poruka tvrtke',
                'noPackages' => 'Nijedan paket nije odabran',
                'priceByAgreement' => 'Po dogovoru',
            ],
            'creator_hired' => [
                'subject' => 'Ponuda je prihvaćena na Waveu',
                'preheader' => 'Tvoj angažman za kampanju je potvrđen.',
                'eyebrow' => 'ANGAŽMAN POTVRĐEN',
                'heading' => 'Čestitamo, angažiran/a si!',
                'greeting' => 'Pozdrav!',
                'message' => 'Tvrtka te angažirala za ovu kampanju nakon što si prihvatio/la ponudu.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Tvrtka',
                'detailsLabel' => 'Status ponude',
                'details' => 'Prihvaćena',
                'buttonLabel' => 'Pogledaj ponudu',
                'footer' => 'Automatska poruka Wavea. Molimo ne odgovaraj na ovu poruku.',
            ],
            'unread_message_reminder' => [
                'subject' => 'Imaš nepročitane poruke na Waveu',
                'preheader' => 'U razgovoru o kampanji čeka te nova poruka.',
                'eyebrow' => 'NEPROČITANE PORUKE',
                'heading' => 'Čeka te nova poruka.',
                'greeting' => 'Pozdrav!',
                'message' => 'U razgovoru o kampanji imaš nepročitane poruke. Otvori Wave i nastavi razgovor.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Pošiljatelj',
                'detailsLabel' => 'Broj nepročitanih poruka',
                'buttonLabel' => 'Otvori razgovor',
                'footer' => 'Automatska poruka Wavea. Molimo ne odgovaraj na ovu poruku.',
            ],
        ],
        'sr' => [
            'application_received' => [
                'subject' => 'Nova prijava za kampanju na Waveu',
                'preheader' => 'Novi kreator se prijavio na tvoju kampanju.',
                'eyebrow' => 'NOVA PRIJAVA',
                'heading' => 'Stigla je nova prijava za kampanju.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj prijavu kreatora i njegovu poruku pre nego što odlučiš o sledećem koraku.',
                'firstLabel' => 'Kreator',
                'secondLabel' => 'Kampanja',
                'detailsLabel' => 'Poruka prijave',
                'buttonLabel' => 'Pregledaj prijave',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'Novi upit za tvoj paket na Waveu',
                'preheader' => 'Kompanija je izabrala paket sa tvog profila.',
                'eyebrow' => 'NOVI UPIT ZA SARADNJU',
                'heading' => 'Kompanija je poslala upit za tvoj paket.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj odabrane pakete, predloženi budžet i poruku kompanije.',
                'firstLabel' => 'Kompanija',
                'secondLabel' => 'Kreator',
                'detailsLabel' => 'Odabrani paketi i poruka',
                'buttonLabel' => 'Pregledaj upite',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
                'selectedPackagesLabel' => 'Odabrani paketi',
                'servicePackage' => 'Paket usluga',
                'otherOption' => 'Nešto drugo',
                'proposedAmountLabel' => 'Predloženi budžet',
                'companyMessageLabel' => 'Poruka kompanije',
                'noPackages' => 'Nijedan paket nije izabran',
                'priceByAgreement' => 'Po dogovoru',
            ],
            'creator_hired' => [
                'subject' => 'Ponuda je prihvaćena na Waveu',
                'preheader' => 'Tvoj angažman za kampanju je potvrđen.',
                'eyebrow' => 'ANGAŽMAN POTVRĐEN',
                'heading' => 'Čestitamo, angažovan/a si!',
                'greeting' => 'Zdravo!',
                'message' => 'Kompanija te je angažovala za ovu kampanju nakon što si prihvatio/la ponudu.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Kompanija',
                'detailsLabel' => 'Status ponude',
                'details' => 'Prihvaćena',
                'buttonLabel' => 'Pogledaj ponudu',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
            'unread_message_reminder' => [
                'subject' => 'Imaš nepročitane poruke na Waveu',
                'preheader' => 'U razgovoru o kampanji čeka te nova poruka.',
                'eyebrow' => 'NEPROČITANE PORUKE',
                'heading' => 'Čeka te nova poruka.',
                'greeting' => 'Zdravo!',
                'message' => 'U razgovoru o kampanji imaš nepročitane poruke. Otvori Wave da nastaviš razgovor.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Pošiljalac',
                'detailsLabel' => 'Broj nepročitanih poruka',
                'buttonLabel' => 'Otvori razgovor',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
        ],
        'cnr' => [
            'application_received' => [
                'subject' => 'Nova prijava za kampanju na Waveu',
                'preheader' => 'Novi kreator se prijavio na tvoju kampanju.',
                'eyebrow' => 'NOVA PRIJAVA',
                'heading' => 'Stigla je nova prijava za kampanju.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj prijavu kreatora i njegovu poruku prije nego što odlučiš o sljedećem koraku.',
                'firstLabel' => 'Kreator',
                'secondLabel' => 'Kampanja',
                'detailsLabel' => 'Poruka prijave',
                'buttonLabel' => 'Pregledaj prijave',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'Novi upit za tvoj paket na Waveu',
                'preheader' => 'Kompanija je izabrala paket sa tvog profila.',
                'eyebrow' => 'NOVI UPIT ZA SARADNJU',
                'heading' => 'Kompanija je poslala upit za tvoj paket.',
                'greeting' => 'Zdravo!',
                'message' => 'Pregledaj odabrane pakete, predloženi budžet i poruku kompanije.',
                'firstLabel' => 'Kompanija',
                'secondLabel' => 'Kreator',
                'detailsLabel' => 'Odabrani paketi i poruka',
                'buttonLabel' => 'Pregledaj upite',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
                'selectedPackagesLabel' => 'Odabrani paketi',
                'servicePackage' => 'Paket usluga',
                'otherOption' => 'Nešto drugo',
                'proposedAmountLabel' => 'Predloženi budžet',
                'companyMessageLabel' => 'Poruka kompanije',
                'noPackages' => 'Nijedan paket nije izabran',
                'priceByAgreement' => 'Po dogovoru',
            ],
            'creator_hired' => [
                'subject' => 'Ponuda je prihvaćena na Waveu',
                'preheader' => 'Tvoj angažman za kampanju je potvrđen.',
                'eyebrow' => 'ANGAŽMAN POTVRĐEN',
                'heading' => 'Čestitamo, angažovan/a si!',
                'greeting' => 'Zdravo!',
                'message' => 'Kompanija te je angažovala za ovu kampanju nakon što si prihvatio/la ponudu.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Kompanija',
                'detailsLabel' => 'Status ponude',
                'details' => 'Prihvaćena',
                'buttonLabel' => 'Pogledaj ponudu',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
            'unread_message_reminder' => [
                'subject' => 'Imaš nepročitane poruke na Waveu',
                'preheader' => 'U razgovoru o kampanji čeka te nova poruka.',
                'eyebrow' => 'NEPROČITANE PORUKE',
                'heading' => 'Čeka te nova poruka.',
                'greeting' => 'Zdravo!',
                'message' => 'U razgovoru o kampanji imaš nepročitane poruke. Otvori Wave da nastaviš razgovor.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Pošiljalac',
                'detailsLabel' => 'Broj nepročitanih poruka',
                'buttonLabel' => 'Otvori razgovor',
                'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
            ],
        ],
        'sl' => [
            'application_received' => [
                'subject' => 'Nova prijava za kampanjo na Waveu',
                'preheader' => 'Nov ustvarjalec se je prijavil na tvojo kampanjo.',
                'eyebrow' => 'NOVA PRIJAVA',
                'heading' => 'Prejeli ste novo prijavo za kampanjo.',
                'greeting' => 'Pozdravljeni!',
                'message' => 'Preglej prijavo ustvarjalca in njegovo sporočilo, preden se odločiš za naslednji korak.',
                'firstLabel' => 'Ustvarjalec',
                'secondLabel' => 'Kampanja',
                'detailsLabel' => 'Sporočilo prijave',
                'buttonLabel' => 'Preglej prijave',
                'footer' => 'To je samodejno sporočilo Wave. Prosimo, ne odgovarjaj nanj.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'Novo povpraševanje za tvoj paket na Waveu',
                'preheader' => 'Podjetje je izbralo paket s tvojega profila.',
                'eyebrow' => 'NOVO POVPRAŠEVANJE',
                'heading' => 'Podjetje je poslalo povpraševanje za tvoj paket.',
                'greeting' => 'Pozdravljeni!',
                'message' => 'Preglej izbrane pakete, predlagani proračun in sporočilo podjetja.',
                'firstLabel' => 'Podjetje',
                'secondLabel' => 'Ustvarjalec',
                'detailsLabel' => 'Izbrani paketi in sporočilo',
                'buttonLabel' => 'Preglej povpraševanja',
                'footer' => 'To je samodejno sporočilo Wave. Prosimo, ne odgovarjaj nanj.',
                'selectedPackagesLabel' => 'Izbrani paketi',
                'servicePackage' => 'Paket storitev',
                'otherOption' => 'Nekaj drugega',
                'proposedAmountLabel' => 'Predlagani proračun',
                'companyMessageLabel' => 'Sporočilo podjetja',
                'noPackages' => 'Noben paket ni izbran',
                'priceByAgreement' => 'Po dogovoru',
            ],
            'creator_hired' => [
                'subject' => 'Ponudba je sprejeta na Waveu',
                'preheader' => 'Tvoje sodelovanje pri kampanji je potrjeno.',
                'eyebrow' => 'SODELOVANJE POTRJENO',
                'heading' => 'Čestitamo, izbran/a si!',
                'greeting' => 'Pozdravljeni!',
                'message' => 'Podjetje te je izbralo za to kampanjo, potem ko si sprejel/a ponudbo.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Podjetje',
                'detailsLabel' => 'Stanje ponudbe',
                'details' => 'Sprejeta',
                'buttonLabel' => 'Oglej si ponudbo',
                'footer' => 'To je samodejno sporočilo Wave. Prosimo, ne odgovarjaj nanj.',
            ],
            'unread_message_reminder' => [
                'subject' => 'Na Waveu imaš neprebrana sporočila',
                'preheader' => 'V pogovoru o kampanji te čaka novo sporočilo.',
                'eyebrow' => 'NEPREBRANA SPOROČILA',
                'heading' => 'Čaka te novo sporočilo.',
                'greeting' => 'Pozdravljeni!',
                'message' => 'V pogovoru o kampanji imaš neprebrana sporočila. Odpri Wave in nadaljuj pogovor.',
                'firstLabel' => 'Kampanja',
                'secondLabel' => 'Pošiljatelj',
                'detailsLabel' => 'Število neprebranih sporočil',
                'buttonLabel' => 'Odpri pogovor',
                'footer' => 'To je samodejno sporočilo Wave. Prosimo, ne odgovarjaj nanj.',
            ],
        ],
        'en' => [
            'application_received' => [
                'subject' => 'New campaign application on Wave',
                'preheader' => 'A new creator has applied to your campaign.',
                'eyebrow' => 'NEW APPLICATION',
                'heading' => 'You received a campaign application.',
                'greeting' => 'Hello!',
                'message' => 'Review the creator and their message before deciding what to do next.',
                'firstLabel' => 'Creator',
                'secondLabel' => 'Campaign',
                'detailsLabel' => 'Application message',
                'buttonLabel' => 'Review applications',
                'footer' => 'This is an automated message from Wave. Please do not reply.',
            ],
            'creator_inquiry_received' => [
                'subject' => 'New package inquiry on Wave',
                'preheader' => 'A company selected a package from your profile.',
                'eyebrow' => 'NEW CREATOR INQUIRY',
                'heading' => 'A company sent you a package inquiry.',
                'greeting' => 'Hello!',
                'message' => 'Review the selected packages, proposed budget, and the company’s message.',
                'firstLabel' => 'Company',
                'secondLabel' => 'Creator',
                'detailsLabel' => 'Selected packages and message',
                'buttonLabel' => 'Review inquiries',
                'footer' => 'This is an automated message from Wave. Please do not reply.',
                'selectedPackagesLabel' => 'Selected packages',
                'servicePackage' => 'Service package',
                'otherOption' => 'Something else',
                'proposedAmountLabel' => 'Proposed budget',
                'companyMessageLabel' => 'Company message',
                'noPackages' => 'No packages selected',
                'priceByAgreement' => 'By agreement',
            ],
            'creator_hired' => [
                'subject' => 'Your offer was accepted on Wave',
                'preheader' => 'Your campaign engagement is confirmed.',
                'eyebrow' => 'ENGAGEMENT CONFIRMED',
                'heading' => 'Congratulations, you are hired!',
                'greeting' => 'Hello!',
                'message' => 'The company has hired you for this campaign after you accepted its offer.',
                'firstLabel' => 'Campaign',
                'secondLabel' => 'Company',
                'detailsLabel' => 'Offer status',
                'details' => 'Accepted',
                'buttonLabel' => 'View offer',
                'footer' => 'This is an automated message from Wave. Please do not reply.',
            ],
            'unread_message_reminder' => [
                'subject' => 'You have unread messages on Wave',
                'preheader' => 'There is a new message waiting in your campaign conversation.',
                'eyebrow' => 'UNREAD MESSAGES',
                'heading' => 'You have a new message.',
                'greeting' => 'Hello!',
                'message' => 'You have unread messages in a campaign conversation. Open Wave to continue the discussion.',
                'firstLabel' => 'Campaign',
                'secondLabel' => 'From',
                'detailsLabel' => 'Unread message count',
                'buttonLabel' => 'Open conversation',
                'footer' => 'This is an automated message from Wave. Please do not reply.',
            ],
        ],
    ];

    private const ACCEPTED_COPY = [
        'bs' => [
            'subject' => 'Tvoj upit za saradnju je prihvaćen na Waveu',
            'preheader' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'eyebrow' => 'UPIT PRIHVAĆEN',
            'heading' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'greeting' => 'Zdravo!',
            'message' => 'Kreator je prihvatio tvoj upit. Otvori upite na Waveu i nastavi razgovor.',
            'firstLabel' => 'Kreator',
            'secondLabel' => 'Kompanija',
            'detailsLabel' => 'Tvoja poruka',
            'buttonLabel' => 'Otvori razgovor',
            'footer' => 'Automatska poruka od Wavea. Molimo ne odgovaraj na ovu e-poruku.',
        ],
        'hr' => [
            'subject' => 'Tvoj upit za suradnju prihvaćen je na Waveu',
            'preheader' => 'Kreator je prihvatio tvoj upit za suradnju.',
            'eyebrow' => 'UPIT PRIHVAĆEN',
            'heading' => 'Kreator je prihvatio tvoj upit za suradnju.',
            'greeting' => 'Pozdrav!',
            'message' => 'Kreator je prihvatio tvoj upit. Otvori upite na Waveu i nastavi razgovor.',
            'firstLabel' => 'Kreator',
            'secondLabel' => 'Tvrtka',
            'detailsLabel' => 'Tvoja poruka',
            'buttonLabel' => 'Otvori razgovor',
            'footer' => 'Automatska poruka Wavea. Molimo ne odgovaraj na ovu poruku.',
        ],
        'sr' => [
            'subject' => 'Tvoj upit za saradnju je prihvaćen na Waveu',
            'preheader' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'eyebrow' => 'UPIT PRIHVAĆEN',
            'heading' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'greeting' => 'Zdravo!',
            'message' => 'Kreator je prihvatio tvoj upit. Otvori upite na Waveu i nastavi razgovor.',
            'firstLabel' => 'Kreator',
            'secondLabel' => 'Kompanija',
            'detailsLabel' => 'Tvoja poruka',
            'buttonLabel' => 'Otvori razgovor',
            'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
        ],
        'cnr' => [
            'subject' => 'Tvoj upit za saradnju je prihvaćen na Waveu',
            'preheader' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'eyebrow' => 'UPIT PRIHVAĆEN',
            'heading' => 'Kreator je prihvatio tvoj upit za saradnju.',
            'greeting' => 'Zdravo!',
            'message' => 'Kreator je prihvatio tvoj upit. Otvori upite na Waveu i nastavi razgovor.',
            'firstLabel' => 'Kreator',
            'secondLabel' => 'Kompanija',
            'detailsLabel' => 'Tvoja poruka',
            'buttonLabel' => 'Otvori razgovor',
            'footer' => 'Automatska poruka od Wavea. Molimo te, ne odgovaraj na ovu e-poruku.',
        ],
        'sl' => [
            'subject' => 'Tvoje povpraševanje za sodelovanje je sprejeto na Waveu',
            'preheader' => 'Ustvarjalec je sprejel tvoje povpraševanje za sodelovanje.',
            'eyebrow' => 'POVPRAŠEVANJE SPREJETO',
            'heading' => 'Ustvarjalec je sprejel tvoje povpraševanje.',
            'greeting' => 'Pozdravljeni!',
            'message' => 'Ustvarjalec je sprejel tvoje povpraševanje. Odpri povpraševanja na Waveu in nadaljuj pogovor.',
            'firstLabel' => 'Ustvarjalec',
            'secondLabel' => 'Podjetje',
            'detailsLabel' => 'Tvoje sporočilo',
            'buttonLabel' => 'Odpri pogovor',
            'footer' => 'To je samodejno sporočilo Wave. Prosimo, ne odgovarjaj nanj.',
        ],
        'en' => [
            'subject' => 'Your collaboration inquiry was accepted on Wave',
            'preheader' => 'The creator accepted your collaboration inquiry.',
            'eyebrow' => 'INQUIRY ACCEPTED',
            'heading' => 'The creator accepted your collaboration inquiry.',
            'greeting' => 'Hello!',
            'message' => 'The creator accepted your inquiry. Open your inquiries on Wave to continue the conversation.',
            'firstLabel' => 'Creator',
            'secondLabel' => 'Company',
            'detailsLabel' => 'Your message',
            'buttonLabel' => 'Open conversation',
            'footer' => 'This is an automated message from Wave. Please do not reply.',
        ],
    ];

    /**
     * @return array<string, string>|null
     */
    public static function forLocale(string $template, string $locale): ?array
    {
        if ($template === 'creator_inquiry_accepted') {
            return self::ACCEPTED_COPY[$locale] ?? null;
        }

        return self::COPY[$locale][$template] ?? null;
    }
}
